### ISSUE TITLE
MacFlim Player sometimes leaves buzzing sound behind after quitting

### ISSUE THREAD

**Issue by RebeccaRGB** [fstark/macflim#8] opened 2021-10-20 03:55 UTC
At least in mini vMac, I haven't tried on real hardware, quitting the player by clicking results in a buzzing sound that persists until shutdown. Probably need to clear out the audio buffer?

**Comment by fstark** [comment] 2021-10-30 12:36
Note: if the version tried was the one one the macflim website (aka beta1, date 2021-09-16), note that there have been a fix in the version in the repository with commit #db21173 on Sept 19 (dubbed beta2, never really released). The one in the repo's dsk had the fix.

**Comment by fstark** [comment] 2021-12-20 22:03
Cannot reproduce, closing. Please re-open if happens again.

**Closed by fstark** 2021-12-20 22:03 UTC
Labels: help wanted, player
